/* Generated By:JavaCC: Do not edit this line. ImacondConstants.java */
package data.constraints;

public interface ImacondConstants {

  int EOF = 0;
  int BAR = 4;
  int COLON = 5;
  int PLUS = 6;
  int NEG = 7;
  int OPENPAR = 8;
  int CLOSEPAR = 9;
  int COMMA = 10;
  int SPACE = 11;
  int CP = 12;
  int CF = 13;
  int IDENT = 14;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"/\"",
    "\":\"",
    "\"+\"",
    "\"!\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\" \"",
    "\"cp\"",
    "\"cf\"",
    "<IDENT>",
  };

}
