<?php

require_once 'script/Roman.php';

require_once "lib/log4php/Logger.php";
Logger::configure(getenv('PHP_INUKTITUT').'/log4php.properties.xml');

/**
 * Test class for Roman.
 * Generated by PHPUnit on 2011-02-01 at 11:48:07.
 */
class RomanTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Roman
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
//        $this->object = new Roman;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testEstVoyelle()
    {
    	$res = Roman::isVowel('i');
    	$this->assertTrue($res,"Erreur : 'i' est une voyelle.");
    }

    /**
     * @todo Implement testNasaleDeSourdeocclusiveLat().
     */
    public function testNasaleDeSourdeocclusiveLat()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSonoreDeSourdeocclusiveLat().
     */
    public function testSonoreDeSourdeocclusiveLat()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
