<?php

require_once 'lib/utf8a.php';

/**
 * Test class for utf8a.
 * Generated by PHPUnit on 2011-01-28 at 16:19:35.
 */
class utf8aTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var utf8a
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new utf8a;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testUtf8_to_numeric().
     */
    public function testUtf8_to_numeric()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testNumeric_to_utf8().
     */
    public function testNumeric_to_utf8()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
